### ISSUE TITLE
Metric specs not supplied

### ISSUE THREAD

**Issue by Amoteamame** [jthomperoo/predictive-horizontal-pod-autoscaler#28]
hi，I use this component to do a test, only one pod is deployed, and the log shows：
15 shell.go:80] Shell command failed, stderr: 2020/06/10 08:30:53 Metric specs not supplied

This is the short part of your experiment, how can I solve it

thanks!

**Comment by Amoteamame** [comment]
> Ah, the [short experiment from here](https://github.com/jthomperoo/custom-pod-autoscaler-experiments/tree/master/predictive-horizontal-pod-autoscaler/short)?
> Good catch, that experiment seems to have a bug in it, it is using the incorrect version of the PHPA - it is targeting `v0.3.0` when it should be targeting `v0.5.0` - I'll push up a change to that in that repository with the fixed version that should work. Sorry about that!

Thank you for your answer!

yes,I’m trying to reproduce this experiment, but when I used v0.5.0,He has a new problem,When i execute:
`python analyse.py`
The following functions report errors:
plot_avg_latency_comparison(horizontal_latencies, predictive_latencies)
plot_max_latency_comparison(horizontal_latencies, predictive_latencies)
plot_failed_to_success_request_percentage(horizontal_latencies, predictive_latencies)

`ValueError: x and y must have same first dimension, but have shapes (60,) and (51,)`

Is there a problem with the settings of my experiment, resulting in different data dimensions?

**Comment by Amoteamame** [comment]
I looked at the data, hpa num requests,hpa avg latencies,hpa max latencies, hpa fail requests .Are 9 lines less data than the corresponding phpa.

**Comment by Amoteamame** [comment]
I looked at the data, hpa num requests,hpa avg latencies,hpa max latencies, hpa fail requests .Are 9 lines less data than the corresponding phpa.

By the way, I did not set these two parameters AUTH_USER and AUTH_PASS, does it affect the experimental results?

**Comment by jthomperoo** [comment]
Hi, sorry for such a late reply! So the issue here is that the short experiment runs locust locally on your machine, and has to use kubectl proxy to be able to hit the endpoints to increase the load on them - really sorry about this, the documentation for that experiment doesn't mention it! I've updated the documentation to show how to use it, again sorry about that!
