### ISSUE TITLE
Custom Pod Autoscaler does not integrate with Argo Rollouts

### ISSUE THREAD

**Issue by MarahAbu** [jthomperoo/predictive-horizontal-pod-autoscaler#52]
**Describe the bug**
custom pod autoscaler does not integrate with argo rollouts.

**To Reproduce**
using argo rollouts

**Expected behavior**
I added rollouts under rules.resources and added argoproj.io under rules.apiGroups in Role I thought it would fix the issue, but still I got: 'no kind "Rollout" is registered for version "argoproj.io/v1alpha1" ' in custom pod autoscaler logs.

**Kubernetes Details (`kubectl version`):**
v1.19.8

**Additional context**
can you please add argo rollouts support?

**Comment by jthomperoo** [comment]
Hey, thanks for raising this, I think this will require work to the underlying Custom Pod Autoscaler that this is built ontop of - I'll investigate and create an issue under that repository so we can hopefully add these changes in soon. I'll keep this issue updated with any changes. Thanks!

**Comment by amitde69** [comment]
any updates on this one ?

**Comment by jthomperoo** [comment]
Hey, sorry had a look at implementing this, hit into this issue reported here: argoproj/argo-workflows#6750.
It seems that the Argo client doesn't play nice with K8s clients v0.21+ which unfortunately this project uses (older versions are deprecated). I think this will be blocked until that's done, but the actual work looks like it could be simple enough once that's done.

You can follow the work done on this for the Custom Pod Autoscaler (the base dependency of this project) here:
https://github.com/jthomperoo/custom-pod-autoscaler/pull/152

After that the jthomperoo/horizontal-pod-autoscaler and jthomperoo/predictive-horizontal-pod-autoscaler would need to be updated, but those should be minor changes.

**Comment by jthomperoo** [comment]
Perhaps not actually blocked by above, downgrading to K8s client `v0.21.8` seems to work. Will try and get a build that hopefully anyone that wants to use this could test out for me.

**Comment by jthomperoo** [comment]
This is now available in the `v0.9.0` release, I've tested as much as I can but have somewhat limited experience with Argo Rollouts - if you can try it out and raise any bugs as issues that would be much appreciated. Thanks!
