### ISSUE TITLE
hook.Definition.Shell  have no  option to send diagnostics/logging to stderr when hook is successful.

### ISSUE THREAD

**Issue by igorshevach** [jthomperoo/predictive-horizontal-pod-autoscaler#61]
**Is your feature request related to a problem? Please describe.**
When a shell hook is executed all logging redirected to stderr (e.g. log.Printf etc) is discarded in case hook was successful.

**Describe the solution you'd like**
Example of hook which does allow for logging a stderr output:
https://pkg.go.dev/github.com/jthomperoo/custom-pod-autoscaler/v2/config#Shell

**Comment by jthomperoo** [comment]
Just wanted to update to say I haven't forgotten about these issues, working on a big update to untangle lots of the dependencies here to allow me to update to the latest Custom Pod Autoscaler version that should let me work through these issues you've raised. Thanks for raising these, it's really useful, and thanks for your patience!

**Comment by jthomperoo** [comment]
Support for shell hooks has been dropped with the migration to PHPAs as an operator focused resource (#69).
