### ISSUE TITLE
holt winters python 3-8 algorithm code fails due to outdated dependencies of statsmodel 0.12.1

### ISSUE THREAD

**Issue by igorshevach** [jthomperoo/predictive-horizontal-pod-autoscaler#64]
**Describe the bug**
running holt winters model errors out with:
Cannot import name '_centered' from 'scipy.signal.signaltools'

**To Reproduce**
1. Deploy latest version of phpa
2. Run holt-winters example
3. See error as described above

**Expected behavior**
holt winters should run to completion without errors

**Kubernetes Details (`kubectl version`):**
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
predictive-horizontal-pod-autoscaler commit a8f581d43d689c8ae439ad12b9d2425d4419949d

**Additional context**
modifying docker image to use cpa python 3-7 instead 3-8 solves the issue, however this is just a workaround.
upgrading to latest statsmodels/scipy or both should solve the issue

**Comment by jthomperoo** [comment]
Resolved by #67

**Comment by jthomperoo** [comment]
This is now available in [v0.10.0](https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/releases/tag/v0.10.0).
