### ISSUE TITLE
Errors in phpa operator pod

### ISSUE THREAD

**Issue by MarahAbu** [jthomperoo/predictive-horizontal-pod-autoscaler#74]
**Describe the bug**
I have these two errors in the phpa operator pod:
- ERROR	failed to get predicted replica count,......,"error": "exit status 1: Traceback (most recent call last):\n  File \"/app/algorithms/holt_winters/holt_winters.py\", line 92, in <module>\n    model = sm.ExponentialSmoothing(algorithm_input.series,\n  File \"/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py\", line 207, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters/model.py\", line 292, in __init__\n    self._initialize()\n  File \"/usr/local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters/model.py\", line 432, in _initialize\n    return self._initialize_heuristic()\n  File \"/usr/local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters/model.py\", line 447, in _initialize_heuristic\n    lvl, trend, seas = _initialization_heuristic(\n  File \"/usr/local/lib/python3.8/site-packages/statsmodels/tsa/exponential_smoothing/initialization.py\", line 59, in _initialization_heuristic\n    raise ValueError('Cannot compute initial seasonals using'\nValueError: Cannot compute initial seasonals using heuristic method with less than two full seasonal cycles in the data.\n"}
- ERROR	failed to update PHPA configmap

**Predictive Horizontal Pod Autoscaler Version**
The version of the Predictive Horizontal Pod Autoscaler the bug has been found on.
v0.11.1

**To Reproduce**
1. Deploy latest phpa version (v0.11.1)
2. Run with holt_winters model
3. See error

**Expected behavior**
num of pods being predicted after two-three load tests without the errors described above

**Kubernetes Details (`kubectl version`):**
Kubernetes version, kubectl version etc.
v1.20

**Additional context**

**Comment by amitde69** [comment]
@jthomperoo any update on this one ?

**Comment by jthomperoo** [comment]
Hi @amitde69 I've identified the issue as being with the Python logic that runs the holt winters calculation - I just haven't had time to address any of the issues in this project for a while since I've been very busy. I'll try to make some time to have a look when I can. 
Thanks!

**Comment by jthomperoo** [comment]
This fix is now available in [`v0.11.2`](https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/releases/tag/v0.11.2), please let me know if your issue is not resolved.
