### ISSUE TITLE
Does PHPA support custom and external metric as k8s HPA?

### ISSUE THREAD

**Issue by wildermesser** [jthomperoo/predictive-horizontal-pod-autoscaler#75]
Currently HPA in Kubernetes supports various metrics sources: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis

Does PHPA support these type of metrics sources? Or only `Resource metrics`?

**Comment by jthomperoo** [comment]
Hi @wildermesser, yes the PHPA supports both custom and external metrics, it relies on the [jthomperoo/k8shorizmetrics](https://github.com/jthomperoo/k8shorizmetrics) project to do that which aims to have parity with the features that the K8s HPA supports. If you encounter any issues/lack of matching support please raise an issue and I'll have a look.

Thanks!
