### ISSUE TITLE
phpa scaledown behavior

### ISSUE THREAD

**Issue by MarahAbu** [jthomperoo/predictive-horizontal-pod-autoscaler#78]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying to set a scaling down behavior which is available in api autoscaling/v2beta2, I tried to add it in the phpa but it's not working so I assume its built on top hpa version autoscaling/v1.

**Describe the solution you'd like**
can you please update the phpa operator so it will allow using the scaling policies?

**Describe alternatives you've considered**
I tried to add the behavior as an annotation in phpa using "autoscaling.alpha.kubernetes.io/behavior" annotation but unfortunately it's not stable.

**Comment by jthomperoo** [comment]
Hi @MarahAbu thanks for raising this.

I'm going to investigate adding scaledown behaviour in, I think this will require upgrading to autoscaling/v2 so I'll need to see how much of an impact that has/if there are breaking changes with that.

**Comment by jthomperoo** [comment]
This has been added in version [`v0.12.0`](https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/releases/tag/v0.12.0).

Thanks for suggesting and raising this!

**Comment by MarahAbu** [comment]
Great, thanks for the quick update
