### ISSUE TITLE
Regarding history size

### ISSUE THREAD

**Issue by 223311** [jthomperoo/predictive-horizontal-pod-autoscaler#96]
Hi friend, I was testing PHPA in one of the EKS clusters and noticed that the history size for the linear regression model is being displayed. I have a few questions regarding this. I would appreciate it if you could provide some details. Thank you.

1. Does PHPA save the history size for the linear regression model in memory, or does it use a config map to store it?
2. In the event of software reinstallation, how can the old data be retrieved?
3. When I run 'kubectl get HPA', the HPA details are not displayed. In this case, how can we determine the current usage of pod and memory?
@jthomperoo

**Comment by jthomperoo** [comment]
Hi @223311,

1. The history is stored in a config map, not in memory, so it is persisted across restarts etc.
2. If you uninstall the PHPA operator/a PHPA any config maps will also be removed, so it is not possible to recover old data. 
3. You can use `kubectl get phpa` to view the PHPAs you have on your system. It does not expose the CPU/memory usage of pods, it only provides these columns:

- Reference = The identifier for the resource being scaled in the format <api-version>/<api-kind/<name>
- Min Pods = The minimum number of replicas of pods that the resource being managed by the autoscaler can have
- Max Pods = The maximum number of replicas of pods that the resource being managed by the autoscaler can have
- Replicas = The desired number of replicas of pods managed by this autoscaler as last calculated by the autoscaler
- Last Scale Time = The last time the PredictiveHorizontalPodAutoscaler scaled the number of pods
